name: Generate translated PDF

on:
  workflow_call:
    inputs:
      keep_alive:
        description: 'docker keep alive'
        required: true
        default: "1"
        type: string
      url:
        description: 'The url of the repo'
        required: true
        default: https://github.com/owaspsamm/core
        type: string
      branch:
        description: 'branch of the repo'
        required: true
        default: main
        type: string
      language:
        description: 'the language'
        default: en
        type: string

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
      # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
      # uses: shivammathur/setup-php@v2
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - uses: actions/checkout@v2
        with:
          repository: owaspsamm/pdf-generator
          ref: main
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Create Database
        run: sh scripts/generate_pdf.sh -a ${{ inputs.keep_alive }} -u ${{ inputs.url }} -b ${{ inputs.branch }} -l ${{ inputs.language }}
      - uses: actions/upload-artifact@v3
        with:
          name: samm.pdf
          path: export/SAMM.pdf
